countries = ['canada', 'chile', 'nepal', 'china', 'brazil', 'ireland']

print(countries)
sorted_countries = sorted(countries)
print(sorted_countries)
print(countries)
reverse_sorted_countries = sorted(countries, reverse=True)
print(reverse_sorted_countries)
print(countries)
countries.reverse()
print(countries)
countries.reverse()
print(countries)
countries.sort()
print(countries)
countries.sort(reverse=True)
print(countries)
